server:
  port: 8082

spring:
  application:
    name: Hotel-Service

  datasource:
    name: hotel_microservicedb
    url: jdbc:mysql://localhost:3306/hotel_microservicedb
    username: root
    password: admin

  jpa:
    hibernate:
      ddl-auto: update

eureka:
  instance:
    prefer-ip-address: true
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka
